name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js 18 environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Run API tests
      - name: Test Api
        run: cd api && yarn install && yarn test

      # Run APP tests
      - name: Test Api
        run: cd app && yarn install && yarn test

  deploy:
    need: build
    runs-on: ubuntu-latest

    steps:
    - uses: appleboy/ssh-action@v1.0.0
      with:
        host: 139.180.156.22
        username: ${{ secrets.DEPLOY_HOST }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --help
          bash ~/deploy.sh
           
