name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js 18 environment
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: cd api && yarn install

      # Run tests
      - name: Run tests
        run: cd api && yarn install

      # Build the application
      - name: Build the application
        run: cd api && yarn install

  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    - name: Deploying
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 139.180.156.22
        username: ${{ secrets.DEPLOY_HOST }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        script: |
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          npm --help
          bash ~/deploy.sh
           
